FROM alpine:latest

ENV TZ=Asia/Shanghai LANG=C.UTF-8
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN mkdir -m 775 /docker-entrypoint.d
COPY --chmod=775 ./docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]
COPY --chmod=775 ./docker-entrypoint.d/ /docker-entrypoint.d/

CMD [ "sh" ]
